services:
  app:
    image: node:18-alpine
    container_name: adonis-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      DB_CONNECTION: pg
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DB_NAME: mydatabase
    command: sh -c "npm install && node ace serve --watch"

  db:
    image: postgres:14
    container_name: postgres-db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"

volumes:
  postgres_volume:
